export { default as Home } from './Home/Home'
export { default as BookPage } from './BookPage/BookPage'
export { default as Login } from './Login/Login'
export { default as Admin } from './Admin/Admin'
export { default as Blog } from './Blog/Blog'